language: node_js

node_js:
  - "node"
  - "6"

before_script:
  - npm install -g phantomjs
  - npm install -g rollup
  - npm install -g karma
  - npm install -g eslint
  - npm install
  - export PATH=/usr/local/phantomjs-2.1.7/bin:$PATH

script:
  - npm run lint
  - npm run test:unit
  - npm run build
